
import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, Sparkles } from 'lucide-react';
import axios from 'axios';
import apiUrl from '@/config/api';

// A placeholder CSS-based animation to stand in for a Lottie file.
const AiOrbAnimation = () => {
  return (
    <div className="relative w-48 h-48 mx-auto">
      <motion.div
        animate={{ rotate: 360 }}
        transition={{ duration: 30, repeat: Infinity, ease: "linear" }}
        className="absolute inset-0 w-full h-full bg-gradient-to-r from-blue-500 to-purple-500 opacity-20 blur-2xl rounded-full"
      />
      <motion.div
        animate={{ rotate: -360 }}
        transition={{ duration: 40, repeat: Infinity, ease: "linear" }}
        className="absolute inset-4 w-40 h-40 bg-gradient-to-r from-pink-500 to-indigo-500 opacity-20 blur-2xl rounded-full"
      />
    </div>
  );
};

const demoQueries = [
  {
    question: "Find Bhagesh Biradar's latest lab results",
    answer: "Example Answer: Bhagesh Biradar's latest lab results from yesterday show a Cholesterol level of 195 mg/dL and Blood Glucose at 95 mg/dL. All other values are within normal ranges."
  },
  {
    question: "Show bed availability in Ward C",
    answer: "Example Answer: There are currently 3 beds available in Ward C: C-102, C-105, and C-112."
  },
  {
    question: "What is Dr. Smith's schedule for tomorrow?",
    answer: "Example Answer: Dr. Smith is scheduled for rounds from 9 AM to 11 AM and has appointments from 2 PM to 5 PM tomorrow."
  }
];

const AiSearchSection = () => {
  // Core state
  const [query, setQuery] = useState('');
  const [isThinking, setIsThinking] = useState(false);
  const [response, setResponse] = useState('');
  
  // Mode state: 'demo' or 'interactive'
  const [mode, setMode] = useState('demo');

  // Demo-specific state
  const [currentQueryIndex, setCurrentQueryIndex] = useState(0);
  const [typedQuery, setTypedQuery] = useState('');
  const inputRef = useRef<HTMLInputElement>(null);

  // This effect runs the demo loop
  useEffect(() => {
    if (mode !== 'demo') return;

    let isCancelled = false;

    const runDemo = async () => {
      // 1. Type out the question
      const current = demoQueries[currentQueryIndex];
      for (let i = 0; i <= current.question.length; i++) {
        if (isCancelled) return;
        setTypedQuery(current.question.substring(0, i));
        await new Promise(r => setTimeout(r, 50));
      }

      // 2. Show "Thinking..." state
      if (isCancelled) return;
      await new Promise(r => setTimeout(r, 500));
      setIsThinking(true);

      // 3. Show the answer
      if (isCancelled) return;
      await new Promise(r => setTimeout(r, 2000));
      setIsThinking(false);
      setResponse(current.answer);

      // 4. Wait and reset for the next loop
      if (isCancelled) return;
      await new Promise(r => setTimeout(r, 5000));
      setResponse('');
      setTypedQuery('');
      setCurrentQueryIndex((prevIndex) => (prevIndex + 1) % demoQueries.length);
    };

    const timeoutId = setTimeout(runDemo, 1000);

    return () => {
      isCancelled = true;
      clearTimeout(timeoutId);
    }; // Cleanup on mode change or unmount
  }, [currentQueryIndex, mode]);

  // Switch to interactive mode and focus the input
  const switchToInteractiveMode = () => {
    if (mode === 'demo') {
      setMode('interactive');
      // Reset demo states
      setTypedQuery('');
      setResponse('');
      setIsThinking(false);
      // Focus the real input field after a short delay
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  };

  // Handle real user search
  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query) return;

    setIsThinking(true);
    setResponse('');

    try {
      const messages = [{ role: 'user', content: query }];
      const apiResponse = await axios.post(apiUrl('/api/ai/ask'), { messages });
      
      const disclaimer = "Disclaimer: This response is generated by a general AI model and is not based on real hospital data.\n\n";
      setResponse(disclaimer + apiResponse.data.reply);

      // Clear the interactive search after a delay
      setTimeout(() => {
        setQuery('');
        setResponse('');
      }, 10000); // 10 seconds

    } catch (error) {
      console.error("AI search error:", error);
      if (axios.isAxiosError(error) && !error.response) {
        setResponse("Failed to connect to the AI service. Please check the server and network.");
      } else {
        setResponse(error.response?.data?.error || "An unknown error occurred.");
      }
    } finally {
      setIsThinking(false);
    }
  };

  return (
    <motion.section id="ai-search" className="py-24 bg-background text-foreground relative overflow-hidden">
      <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        
        <AiOrbAnimation />

        <h2 className="text-4xl md:text-5xl font-bold mt-8">
          Shree Medicare, <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">Powered by Conversational AI</span>
        </h2>
        <p className="text-xl text-slate-400 mt-4">
          This is a demonstration of our new AI assistant. Soon, you'll be able to ask questions about patients, staff schedules, and ward availability to get immediate, accurate answers.
        </p>

        <div className="mt-12 w-full max-w-2xl mx-auto" onClick={switchToInteractiveMode}>
          {mode === 'demo' ? (
            <div className="relative cursor-pointer">
              <div className="w-full pl-6 pr-14 py-4 bg-slate-800/50 border border-slate-700 rounded-full shadow-lg text-left">
                <span className="text-lg text-slate-300">{typedQuery}</span>
                <span className="animate-pulse">|</span>
              </div>
              <div className="absolute right-3 top-1/2 -translate-y-1/2 p-2 bg-blue-600 rounded-full">
                <Search className="w-5 h-5 text-white" />
              </div>
            </div>
          ) : (
            <form onSubmit={handleSearch}>
              <div className="relative">
                <input
                  ref={inputRef}
                  type="text"
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  className="w-full pl-6 pr-14 py-4 bg-slate-800/50 border border-slate-700 rounded-full shadow-lg focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all placeholder:text-slate-500 text-lg"
                  placeholder='Ask anything...'
                />
                <button type="submit" className="absolute right-3 top-1/2 -translate-y-1/2 p-2 bg-blue-600 rounded-full hover:bg-blue-700 transition-colors">
                  <Search className="w-5 h-5 text-white" />
                </button>
              </div>
            </form>
          )}
        </div>

        <div className="mt-8 min-h-[150px]">
          <AnimatePresence>
            {isThinking && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="flex items-center justify-center gap-2 text-slate-400"
              >
                <span className="font-semibold">Thinking</span>
                <motion.div animate={{ y: [0, -4, 0] }} transition={{ duration: 0.8, repeat: Infinity, ease: "easeInOut" }} className="w-2 h-2 bg-slate-500 rounded-full" />
                <motion.div animate={{ y: [0, -4, 0] }} transition={{ duration: 0.8, repeat: Infinity, ease: "easeInOut", delay: 0.1 }} className="w-2 h-2 bg-slate-500 rounded-full" />
                <motion.div animate={{ y: [0, -4, 0] }} transition={{ duration: 0.8, repeat: Infinity, ease: "easeInOut", delay: 0.2 }} className="w-2 h-2 bg-slate-500 rounded-full" />
              </motion.div>
            )}
          </AnimatePresence>
          <AnimatePresence>
            {response && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, ease: "easeOut" }}
                className="mt-4 p-6 text-left bg-slate-800/50 border border-slate-700 rounded-xl shadow-lg max-w-lg mx-auto"
              >
                <div className="text-slate-300 whitespace-pre-wrap">{response}</div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

      </div>
    </motion.section>
  );
};

export default AiSearchSection;
