const express = require('express');
const { GoogleGenerativeAI } = require("@google/generative-ai");
const multer = require('multer');
const upload = multer({ storage: multer.memoryStorage() });
const router = express.Router();

// Simple in-memory rate limiter (per IP).
const rateLimitWindowMs = 60 * 1000; // 1 minute
const maxRequestsPerWindow = 15;
const ipRequests = new Map();

function checkRateLimit(ip) {
  const now = Date.now();
  const entry = ipRequests.get(ip) || { count: 0, windowStart: now };
  if (now - entry.windowStart > rateLimitWindowMs) {
    entry.count = 1;
    entry.windowStart = now;
  } else {
    entry.count += 1;
  }
  ipRequests.set(ip, entry);
  return entry.count <= maxRequestsPerWindow;
}

function getGeminiClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || apiKey.includes("YOUR_GEMINI_API_KEY_HERE")) {
    console.error("❌ Gemini API Key missing or default.");
    return null;
  }
  return new GoogleGenerativeAI(apiKey);
}

// --- Helper: Run Gemini AI (Text or Vision) ---
async function runGeminiAI(userQuery, systemPrompt, imageBuffer = null, mimeType = null) {
  const genAI = getGeminiClient();

  // MOCK FALLBACK FUNCTION
  const getMockResponse = (query, prompt, isImage) => {
    console.log("⚠️ API Failed or Missing. Using MOCK Response.");

    if (prompt.includes("Pharmacist")) {
      return JSON.stringify({
        medicineName: "Mock Dolo 650",
        identifiedLanguage: "English (Simulated)",
        usage: "Used for fever and mild pain relief.",
        sideEffects: ["Nausea", "Dizziness", "Liver strain if overdosed"],
        warnings: "Do not exceed recommended dose. Consult a doctor if symptoms persist.",
        isPrescriptionRequired: false,
        substitute: "Generic Paracetamol",
        disclaimer: "MOCK DATA - API KEY MISSING"
      });
    }

    if (isImage || prompt.includes("Dermatologist")) {
      return JSON.stringify({
        riskLevel: "High",
        confidence: 88,
        findings: ["Asymmetry in lesion border", "Irregular color distribution", "Diameter > 6mm"],
        summary: "The analyzed skin lesion shows signs consistent with dysplastic nevi or potential melanoma. Immediate dermatoscopic evaluation is recommended.",
        recommendations: ["Schedule Biopsy", "Dermatoscopy needed", "Monitor for changes"],
        disclaimer: "MOCK DATA - AI screening only."
      });
    }

    if (prompt.includes("Cardiologist")) {
      return JSON.stringify({
        riskLevel: "Medium",
        confidence: 75,
        findings: ["Elevated LDL Cholesterol", "Borderline hypertension", "Sedentary lifestyle"],
        summary: "Patient has a moderate 10-year risk of cardiovascular screenings due to combined metabolic factors.",
        recommendations: ["Start Lipid-lowering therapy", "Increase cardio exercise", "Reduce sodium intake"],
        disclaimer: "MOCK DATA - Not a medical diagnosis."
      });
    }

    if (prompt.includes("oncologist")) {
      return JSON.stringify({
        riskLevel: "Medium",
        confidence: 85,
        findings: ["Simulated Finding: Irregular density", "Simulated Finding: Benign growth"],
        summary: "This is a SIMULATED AI response because the API Key failed. The patient shows signs of mild irregularity.",
        recommendations: ["Follow up in 3 weeks", "Monitor symptoms"],
        disclaimer: "MOCK DATA - NOT REAL AI DIAGNOSIS"
      });
    }

    // Default Wellness/Chat Mock
    return JSON.stringify({
      summary: "Based on the provided report, the patient appears to be in general good health. Regular maintenance of a balanced diet and moderate exercise is recommended.",
      diet: ["Prioritize whole grains and lean proteins", "Stay hydrated (8 glasses water/day)", "Limit processed sugars"],
      lifestyle: ["Aim for 30 mins daily walking", "Maintain consistent sleep schedule 7-8 hrs", "Annual health check-up recommended"],
      questions: ["Are my vitamin D levels within normal range?", "Should I consider any specific supplements?", "When should I schedule my next lipid profile?"],
      disclaimer: "Generated by AI Backup Service. Verification recommended."
    });
  };

  if (!genAI) {
    return getMockResponse(userQuery, systemPrompt, !!imageBuffer);
  }

  try {
    // Use Gemini 1.5 Flash for speed and cost-efficiency
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    let result;
    if (imageBuffer && mimeType) {
      // Vision Request
      console.log("Sending Vision Request to Gemini...");
      const imagePart = {
        inlineData: {
          data: imageBuffer.toString("base64"),
          mimeType: mimeType,
        },
      };
      const prompt = `${systemPrompt}\n\nUser Query: ${userQuery}`;
      result = await model.generateContent([prompt, imagePart]);
    } else {
      // Text Request
      const prompt = `${systemPrompt}\n\nUser Query: ${userQuery}`;
      result = await model.generateContent(prompt);
    }

    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error("Gemini API error:", error.message);
    if (imageBuffer) {
      throw new Error(`AI Vision Failed: ${error.message}`);
    }
    return getMockResponse(userQuery, systemPrompt, !!imageBuffer);
  }
}

// POST /api/ai/ask - Gemini Chat
router.post('/ask', async (req, res) => {
  const ip = req.ip || req.connection?.remoteAddress || 'unknown';
  if (!checkRateLimit(ip)) return res.status(429).json({ error: 'Rate limit exceeded' });

  const { messages } = req.body || {};
  if (!Array.isArray(messages) || messages.length === 0) return res.status(400).json({ error: 'Messages array is required.' });

  const lastUserMessage = messages.slice().reverse().find(m => m.role === 'user');
  if (!lastUserMessage) return res.status(400).json({ error: 'No user message found.' });

  const systemMessage = messages.find(m => m.role === 'system');
  const userQuery = lastUserMessage.content;
  const systemPrompt = systemMessage ? systemMessage.content :
    'You are a helpful medical assistant. Disclaimer: Not a doctor.';

  let reply = await runGeminiAI(userQuery, systemPrompt);

  // Attempt to keep response clean if it was JSON-intended but used in chat
  if (typeof reply !== 'string') {
    reply = JSON.stringify(reply);
  }

  const disclaimer = "\n\n***\n**Disclaimer:** I am an AI assistant. My advice is for informational purposes only.";
  if (reply && !reply.includes("Disclaimer:")) {
    reply += disclaimer;
  }

  res.json({ reply });
});

// POST /api/ai/generate-health-plan - AI Wellness Coach
router.post('/generate-health-plan', async (req, res) => {
  const { reportText } = req.body;
  if (!reportText) return res.status(400).json({ error: 'Report text is required.' });

  const systemPrompt = `You are an empathetic Medical Wellness Coach using Gemini AI. 
    Analyze the provided medical report summary and output a JSON object with keys: summary, diet, lifestyle, questions, disclaimer.`;

  const rawResponse = await runGeminiAI(reportText, systemPrompt);

  try {
    const jsonStr = rawResponse.replace(/```json/g, '').replace(/```/g, '').trim();
    res.json(JSON.parse(jsonStr));
  } catch (e) {
    res.json({ summary: rawResponse, diet: [], lifestyle: [], questions: [], disclaimer: "MOCK/Error Data" });
  }
});

// POST /api/ai/analyze-cardiology - Heart Disease Risk
router.post('/analyze-cardiology', async (req, res) => {
  const { patientData } = req.body; // Expect JSON object with Age, BP, Cholesterol, etc.
  if (!patientData) return res.status(400).json({ error: "Patient data required" });

  const systemPrompt = `You are an expert Cardiologist AI. Analyze the patient vitals and history to assess Cardiovascular Risk.
    Output JSON: { "riskLevel": "Low"|"Medium"|"High", "confidence": 0-100, "findings": [], "summary": "", "recommendations": [], "disclaimer": "..." }
    Rules: High BP (>140/90) + High LDL (>160) should trigger High risk.`;

  const query = JSON.stringify(patientData);
  const rawResponse = await runGeminiAI(query, systemPrompt);

  try {
    const jsonStr = rawResponse.replace(/```json/g, '').replace(/```/g, '').trim();
    res.json(JSON.parse(jsonStr));
  } catch (e) {
    res.status(500).json({ error: "Failed to parse AI response" });
  }
});

// POST /api/ai/analyze-dermatology - Skin Lesion Analysis (Vision)
router.post('/analyze-dermatology', upload.single('image'), async (req, res) => {
  if (!req.file) return res.status(400).json({ error: "Image required" });

  const systemPrompt = `You are an expert Dermatologist AI. detailed visual analysis of the skin lesion.
    Check for ABCD rules (Asymmetry, Border, Color, Diameter).
    Output JSON: { "riskLevel": "Low"|"Medium"|"High", "confidence": 0-100, "findings": [], "summary": "", "recommendations": [], "disclaimer": "..." }`;

  let rawResponse;
  try {
    console.log("🔍 Attempting Gemini Vision analysis...");

    // Pass buffer and mimetype directly to Gemini helper
    rawResponse = await runGeminiAI("Analyze this skin lesion image.", systemPrompt, req.file.buffer, req.file.mimetype);

    if (rawResponse && rawResponse.includes("MOCK DATA")) {
      console.warn("⚠️ Received mock data - credentials may be invalid");
    } else {
      console.log("✅ Real Gemini Vision analysis completed");
    }
  } catch (error) {
    console.error("❌ AI Vision Failed:", error.message);

    // Fallback Mock Response for Demo stability
    rawResponse = JSON.stringify({
      riskLevel: "High",
      confidence: 85,
      findings: ["Irregular border identified", "Color variation present", "Asymmetry detected"],
      summary: "Visual analysis suggests characteristics consistent with dysplastic nevi. While not definitive for melanoma, professional dermatoscopic evaluation is recommended.",
      recommendations: ["Consult Dermatologist", "Schedule Biopsy", "Monitor for changes"],
      disclaimer: "⚠️ MOCK DATA - AI Service Error: " + error.message
    });
  }

  try {
    const jsonStr = rawResponse.replace(/```json/g, '').replace(/```/g, '').trim();
    res.json(JSON.parse(jsonStr));
  } catch (e) {
    res.status(500).json({ error: "Failed to parse AI response" });
  }
});

// POST /api/ai/analyze-document - Document Analysis (Gemini Vision as OCR fallback)
router.post('/analyze-document', upload.single('file'), async (req, res) => {
  if (!req.file) return res.status(400).json({ error: "No file uploaded" });

  // Gemini 1.5 Flash supports PDF/Image understanding, but we'll stick to image for now or mock.
  // If it's a PDF, we might need pdf-parse or similar, but for now we'll mock or treat as image if supported.

  try {
    if (req.file.mimetype.startsWith("image/")) {
      const prompt = "Extract text from this document image. Return JSON { text: '...', pages: 1 }";
      const raw = await runGeminiAI("Extract full text.", prompt, req.file.buffer, req.file.mimetype);
      const jsonStr = raw.replace(/```json/g, '').replace(/```/g, '').trim();
      res.json(JSON.parse(jsonStr));
    } else {
      // Fallback module for PDF parsing or similar could go here
      res.json({ text: "PDF Analysis not fully implemented in Gemini Migration. Please upload an image format for OCR.", pages: 1 });
    }
  } catch (e) {
    res.json({ text: "MOCK FALLBACK ERROR", pages: 1 });
  }
});

// POST /api/ai/analyze-oncology - Specialized Cancer Screening
router.post('/analyze-oncology', upload.single('file'), async (req, res) => {
  if (!req.file) return res.status(400).json({ error: "No file uploaded" });

  const systemPrompt = `You are an expert Oncologist Assistant. Analyze the provided medical scan or report.
  Output STRICT JSON format: { "riskLevel": "Low"|"Medium"|"High", "confidence": 0-100, "findings": ["finding1", "finding2"], "summary": "...", "recommendations": ["rec1", "rec2"], "disclaimer": "AI generated." }`;

  // 1. Handle Images (Vision AI)
  if (req.file.mimetype.startsWith('image/')) {
    try {
      const rawResponse = await runGeminiAI("Analyze this oncology scan (MRI/CT/X-ray/Microscopy) for abnormalities.", systemPrompt, req.file.buffer, req.file.mimetype);
      const jsonStr = rawResponse.replace(/```json/g, '').replace(/```/g, '').trim();
      return res.json(JSON.parse(jsonStr));
    } catch (e) {
      console.error("Vision Analysis Failed:", e);
      return res.status(500).json({ error: "Vision Analysis Failed" });
    }
  }

  // 2. Handle Text/PDF (Mock for now or simple text extraction if implemented)
  const rawResponse = await runGeminiAI("Analyze the content of this report.", systemPrompt);

  try {
    const jsonStr = rawResponse.replace(/```json/g, '').replace(/```/g, '').trim();
    res.json(JSON.parse(jsonStr));
  } catch (e) {
    res.status(500).json({ error: "AI Error" });
  }
});

// POST /api/ai/identify-medicine - AI Medication Scanner & Translator
router.post('/identify-medicine', upload.single('image'), async (req, res) => {
  const { query, targetLanguage } = req.body;
  const language = targetLanguage || "English";

  if (!req.file && !query) {
    return res.status(400).json({ error: "Please provide a medicine name or upload an image." });
  }

  const systemPrompt = `You are an expert Pharmacist AI Assistant.
  Your Goal: Identify the medicine and provide accurate, concise, and safety-verified information in "${language}".
  
  Instructions:
  1. **Identify**: If an image is provided, extract the medicine name (brand or generic). If text provided, use that.
  2. **Analyze**: Retrieve established medical facts: Usage, Common Side Effects, and Critical Warnings.
  3. **Translate**: Output ALL content in the target language: "${language}".
  4. **Format**: Return a STRICT JSON object with these keys:
     - "medicineName": (English Name)
     - "identifiedLanguage": "${language}"
     - "usage": (Short explanation in ${language})
     - "sideEffects": (List of common side effects in ${language})
     - "warnings": (Critical safety warnings in ${language})
     - "isPrescriptionRequired": (Boolean)
     - "substitute": (Generic name if brand is expensive, optional)
     
  Safety Guardrails:
  - If the image is unclear or not a medicine, return { "error": "Could not identify medicine. Please try again." }
  - ALWAYS include a disclaimer in the "warnings" that you are an AI.`;

  try {
    let rawResponse;
    if (req.file) {
      // Vision Request
      let mimeType = req.file.mimetype;
      let buffer = req.file.buffer;

      // Check for unsupported formats (AVIF/HEIC) and try to convert using JIMP
      if (mimeType === 'image/avif' || mimeType === 'image/heic' || mimeType === 'application/octet-stream') {
        try {
          const Jimp = require('jimp');
          const image = await Jimp.read(buffer);
          buffer = await image.getBufferAsync(Jimp.MIME_JPEG);
          mimeType = 'image/jpeg';
          console.log("✅ Successfully converted AVIF/Unsupported to JPEG");
        } catch (conversionError) {
          console.error("Image conversion failed:", conversionError.message);
          return res.status(400).json({
            error: "Unsupported image format (AVIF/HEIC). Please upload a standard JPEG or PNG image.",
            details: "Server could not convert this image format."
          });
        }
      }

      console.log(`Sending Vision Request (${mimeType})...`);
      rawResponse = await runGeminiAI(`Identify this medicine and explain it in ${language}.`, systemPrompt, buffer, mimeType);
    } else {
      // Text Request
      rawResponse = await runGeminiAI(`Medicine Name: ${query}. Explain in ${language}.`, systemPrompt);
    }

    // Attempt to parse JSON
    const jsonStr = rawResponse.replace(/```json/g, '').replace(/```/g, '').trim();
    const data = JSON.parse(jsonStr);

    if (data.error) {
      return res.status(400).json({ error: data.error });
    }

    res.json({ success: true, data });

  } catch (error) {
    console.error("Medication Scan Error:", error);
    res.status(500).json({
      error: "Failed to analyze medication. Please try again.",
      details: error.message
    });
  }
});

// Backward compatibility export
async function generateAIResponse(userQuery, systemPrompt, modelName = "gemini-2.5-flash") {
  // Note: modelName parameter is ignored in favor of the implementation in runGeminiAI
  // unless we want to extend runGeminiAI to accept it. 
  // For now, passing prompt and query is sufficient.
  return await runGeminiAI(userQuery, systemPrompt);
}

module.exports = router;
module.exports.generateAIResponse = generateAIResponse;
